# Don't want this to be in the repo with the other files as it gets automatically generated
$(IFIOC_GALIL_01) epicsEnvSet "LOOKUPFILE" "c:/instrument/var/tmp/sample.txt"
$(IFIOC_GALIL_01) motionSetPointsConfigure("LOOKUPFILE","LOOKUPFILE")
$(IFIOC_GALIL_01) dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPoints.db","P=$(MYPVPREFIX)LKUP:SAMPLE:,TARGET_PV1=$(MYPVPREFIX)MOT:SC:X:MTR,TARGET_RBV1=$(MYPVPREFIX)MOT:SC:X:MTR.RBV,TARGET_DONE=$(MYPVPREFIX)MOT:SC:X:MTR.DMOV,TARGET_PV2=$(MYPVPREFIX)MOT:SC:Y:MTR,TARGET_RBV2=$(MYPVPREFIX)MOT:SC:Y:MTR.RBV,TARGET_DONE2=$(MYPVPREFIX)MOT:SC:Y:MTR.DMOV,TOL=1,LOOKUP=LOOKUPFILE")
