# $(ICPCONFIGDIR) or $(ICPCONFIGROOT) ?
$(IFDMC06) epicsEnvSet "LOOKUPFILE1" "$(ICPCONFIGROOT)/motionSetPoints/monitor3.txt"
$(IFDMC06) epicsEnvSet "LOOKUPFILE2" "$(ICPCONFIGROOT)/motionSetPoints/monitor4.txt"
$(IFDMC05) epicsEnvSet "LOOKUPFILE3" "$(ICPCONFIGROOT)/motionSetPoints/sample.txt"
$(IFDMC06) epicsEnvSet "LOOKUPFILE5" "$(ICPCONFIGROOT)/motionSetPoints/analyser.txt"
$(IFDMC06) epicsEnvSet "LOOKUPFILE6" "$(ICPCONFIGROOT)/motionSetPoints/polariser.txt"
$(IFDMC06) epicsEnvSet "LOOKUPFILE7" "$(ICPCONFIGROOT)/motionSetPoints/beamstop.txt"
$(IFDMC08) epicsEnvSet "LOOKUPFILE8" "$(ICPCONFIGROOT)/motionSetPoints/linsample.txt"

$(IFDMC06) motionSetPointsConfigure("LOOKUPFILE1","LOOKUPFILE1", 1)
$(IFDMC06) motionSetPointsConfigure("LOOKUPFILE2","LOOKUPFILE2", 1)
$(IFDMC05) motionSetPointsConfigure("LOOKUPFILE3","LOOKUPFILE3", 2)
$(IFDMC06) motionSetPointsConfigure("LOOKUPFILE5","LOOKUPFILE5", 2)
$(IFDMC06) motionSetPointsConfigure("LOOKUPFILE6","LOOKUPFILE6", 2)
$(IFDMC06) motionSetPointsConfigure("LOOKUPFILE7","LOOKUPFILE7", 2)
$(IFDMC08) motionSetPointsConfigure("LOOKUPFILE8","LOOKUPFILE8", 1)

$(IFDMC06) dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPointsSingleAxis.db","P=$(MYPVPREFIX)LKUP:MON3:,AXIS0=$(MYPVPREFIX)MOT:0601,TOL=1,LOOKUP=LOOKUPFILE1")
$(IFDMC06) dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPointsSingleAxis.db","P=$(MYPVPREFIX)LKUP:MON4:,AXIS0=$(MYPVPREFIX)MOT:0602,TOL=1,LOOKUP=LOOKUPFILE2")

$(IFDMC05) dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPointsDoubleAxis.db","P=$(MYPVPREFIX)LKUP:SAMPLE:,AXIS0=$(MYPVPREFIX)MOT:STACK:Y,AXIS1=$(MYPVPREFIX)MOT:STACK:ZLO,TOL=1,LOOKUP=LOOKUPFILE3")

$(IFDMC08) dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPointsSingleAxis.db","P=$(MYPVPREFIX)LKUP:LSAMPLE:,AXIS0=$(MYPVPREFIX)MOT:STACK:LIN,TOL=1,LOOKUP=LOOKUPFILE8")

$(IFDMC06) dbLoadRecords("$(MOTIONSETPOINTS)/db/analyserPolariser.db","D=$(MYPVPREFIX)MOT:ANALYSER:,M=$(MYPVPREFIX)MOT:MTR0605,H=360.5")
$(IFDMC06) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=AX:ANALYSER:THETA,mAXIS=ANALYSER:THETA")

$(IFDMC06) dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPointsDoubleAxis.db","P=$(MYPVPREFIX)LKUP:ANALYSER:,AXIS0=$(MYPVPREFIX)MOT:0606,AXIS1=$(MYPVPREFIX)MOT:AX:ANALYSER:THETA,TOL=1,LOOKUP=LOOKUPFILE5")

$(IFDMC06) dbLoadRecords("$(MOTIONSETPOINTS)/db/analyserPolariser.db","D=$(MYPVPREFIX)MOT:POLARISER:,M=$(MYPVPREFIX)MOT:MTR0604,H=1087")
$(IFDMC06) dbLoadRecords("$(AXIS)/db/axis.db","P=$(MYPVPREFIX)MOT:,AXIS=AX:POLARISER:THETA,mAXIS=POLARISER:THETA")

$(IFDMC06) dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPointsDoubleAxis.db","P=$(MYPVPREFIX)LKUP:POLARISER:,AXIS0=$(MYPVPREFIX)MOT:0603,AXIS1=$(MYPVPREFIX)MOT:AX:POLARISER:THETA,TOL=1,LOOKUP=LOOKUPFILE6")

$(IFDMC06) dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPointsDoubleAxis.db","P=$(MYPVPREFIX)LKUP:BEAMSTOP:,AXIS0=$(MYPVPREFIX)MOT:0607,AXIS1=$(MYPVPREFIX)MOT:0608,TOL=1,LOOKUP=LOOKUPFILE7")
